Spring:
  datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace

jwt:
  private-key-path: classpath:jwt/private.pem
  public-key-path: classpath:jwt/public.pem
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

image:
  upload-dir: "C:/Users/사용자/Desktop/uploads/"
